### ISSUE TITLE
Strip unnecessary quotation and space from caller number?

### ISSUE THREAD

**Issue by Jxck-S** [dshokouhi/pyobihai#4]
Is it possible that you could add a strip to the caller number string, It seems unnecessary that its their and this seems like an easy fix.

**Comment by dshokouhi** [comment]
We dont do any special filtering or replacement, whatever data the device provides is what we send back.  The extra space you see is because some numbers come with extra caller ID info and others do not.  If you feel this should be fixed in another way I would be happy to look at a PR.

**Comment by Jxck-S** [comment]
Yeah i'm gonna try some things, I don't code stuff for HA, where would this module be found in HA, so I could edit it?

**Comment by dshokouhi** [comment]
The fix would get submitted in this repo, then once merged a new version would get published to PYPI then in HA code base we will then need to bump the version there.

**Comment by dshokouhi** [comment]
Fixed in #6 thanks for the PR!  `1.3.1` is now on pypi.
